replicaCount: 1
image:
  repository: ghcr.io/mattjeanes/youtubedl/youtubedl.web
  tag: latest
  pullPolicy: Always
ingress:
  path: /
  pathType: ImplementationSpecific
resources:
  requests:
    memory: 150Mi
    cpu: 10m
